# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngine < Formula
  desc "Engine for ArcadeAI"
  homepage "https://arcade-ai.com/"
  version "0.0.12"

  on_macos do
    on_intel do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Darwin_x86_64.tar.gz"
      sha256 "310574b05b426be5dea8ac6199ff2448c5a8dd72702f0fc008edd5ca58196b9f"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
    on_arm do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Darwin_arm64.tar.gz"
      sha256 "4b1dd6864279b552ffe522bf9a82e916918d6e307caf52593cdec088e48fe6a5"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Linux_x86_64.tar.gz"
        sha256 "81c1ae495f170740a32716fae33df89a52788917b8c66c11b9a52479b8a7ebb7"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Linux_armv6.tar.gz"
        sha256 "8a5f1b7127ea34ca9e1cc4736bfd8490c50b06b9c353d3f0806280231c6ab9ab"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Linux_arm64.tar.gz"
        sha256 "1a22b0da1cb9c9d3bb5a79ba4568dd85bd180f2aefb107a3025b2470b0bd676b"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/arcade-ai.git"
end
