# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngine < Formula
  desc "Engine for ArcadeAI"
  homepage "https://arcade-ai.com/"
  version "0.0.12"

  on_macos do
    on_intel do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Darwin_x86_64.tar.gz"
      sha256 "2099e49f1470fc852fedecbcfacf95e2471a3711943e9d9e6adf5c0d0499b2db"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
    on_arm do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Darwin_arm64.tar.gz"
      sha256 "18ffb3c4c9368d149f3004ca8a1437efed3e3b3fabbfa70a57a688c6023cf58c"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Linux_x86_64.tar.gz"
        sha256 "396e8ebc7c513e00b6131982d4cbefe072ab6a40f419606759d118adda1185e4"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Linux_armv6.tar.gz"
        sha256 "de0c85c6fa8b53178daae4d2fd8ea4f980ccac24ab30facd875ed0fff8bda1e5"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.12/arcade-engine_0.0.12_Linux_arm64.tar.gz"
        sha256 "c9427436e320d8a40f0a7feeefd99b36390c241324759b6e1a0aff3ef0280488"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/arcade-ai.git"
end
