# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT133 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.3.3"
  depends_on :macos

  on_arm do
    url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.3/arcade-engine_1.3.3_Darwin_arm64.tar.gz"
    sha256 "9365a942f269a0e3b01dc7a60d974465b99113c72d6240ff795655a0c9efd19f"

    def install
      bin.install "arcade-engine"
      pkgetc.install 'engine.yaml'
      pkgetc.install 'engine.env'
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
