# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3325 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.25"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.25/arcade-engine_3.3.25_Darwin_x86_64.tar.gz"
      sha256 "6d4b1496753f467eb844990c25edbfcc863cfda5471ccc32fa5dcc3b1a120599"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.25/arcade-engine_3.3.25_Darwin_arm64.tar.gz"
      sha256 "fffd6e6c38e455aff59259dc04ba2073a9174f5f85cd15f443edc6a0d8f45a79"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.25/arcade-engine_3.3.25_Linux_x86_64.tar.gz"
      sha256 "dc9bb2bb072628838b04ffc74be0553713511d74306d2ef0a8c3cf3af594abc3"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.25/arcade-engine_3.3.25_Linux_arm64.tar.gz"
      sha256 "57c510ef3834e7d5c9d4b844277059733e6295e2f3f543e9be919afe5332e5f3"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
