# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3312 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.12/arcade-engine_3.3.12_Darwin_x86_64.tar.gz"
      sha256 "f04eedeabe935a334189c5614c134b4038d6dfd57792e2eb75b09bc842436fa6"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.12/arcade-engine_3.3.12_Darwin_arm64.tar.gz"
      sha256 "c82e17696139fea867b8a768170123b6dfd62fff4b04b787c4883c0898eeaff2"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.12/arcade-engine_3.3.12_Linux_x86_64.tar.gz"
      sha256 "64c66f2a3759018b6787ec321ac7cbd253043394067495688f137544924746a5"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.12/arcade-engine_3.3.12_Linux_arm64.tar.gz"
      sha256 "06ccb9520e2689002ffb4e6a58ae20679783293d8897957fb1fca5b4fdecf8b6"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
