# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT109 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.9/arcade-engine_1.0.9_Darwin_x86_64.tar.gz"
      sha256 "bd3cd40e570de8be38501b090222bd69c929ce83e467304c293cef4dc4dd1795"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.9/arcade-engine_1.0.9_Darwin_arm64.tar.gz"
      sha256 "a369781e41be3919079bd5d8d97badfb72c498c83ea72c4ae6481f2e450fd7d7"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.9/arcade-engine_1.0.9_Linux_x86_64.tar.gz"
        sha256 "c47ba0b42317ebafc3bd9f478116f2b49ea87af77bc2a250b4607e1621c0e6d5"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
