# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3316 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.16/arcade-engine_3.3.16_Darwin_x86_64.tar.gz"
      sha256 "d10c020929a74f98467031a6344ac589b2e4b47988396d44e9db4691a72f00c8"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.16/arcade-engine_3.3.16_Darwin_arm64.tar.gz"
      sha256 "43f5681b10dc743a401bdfbc0512dee79b1e3f05418edf5b56587a5cd02aead3"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.16/arcade-engine_3.3.16_Linux_x86_64.tar.gz"
      sha256 "fff75e2b0f94ffb8b850904e70ea214392d79c03f7a7c4049e6256e4f136c555"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.16/arcade-engine_3.3.16_Linux_arm64.tar.gz"
      sha256 "f0094a06f6f3f0eff410c931c4b6d923eef8e52e8e780a4c51b3305583d4d2c8"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
