# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT0013 < Formula
  desc "Engine for ArcadeAI"
  homepage "https://arcade-ai.com/"
  version "0.0.13"

  on_macos do
    on_intel do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.13/arcade-engine_0.0.13_Darwin_x86_64.tar.gz"
      sha256 "d3adf4bd912f36c05643c958eb007b2ee553968cd70d693dc6fb77626d9ee638"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
    on_arm do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.13/arcade-engine_0.0.13_Darwin_arm64.tar.gz"
      sha256 "126b3309a01525d9825b7d6f671aa753f604a2feb655181d28f584260c8852ea"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.13/arcade-engine_0.0.13_Linux_x86_64.tar.gz"
        sha256 "c428b77588555f2445fdafb3d0986ba52e6c75790f559f47760a1c3deb55bfc3"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.13/arcade-engine_0.0.13_Linux_armv6.tar.gz"
        sha256 "9dddc2a672969f8e6a3bbecb733821adedcd49e3be4e2ced2a98b7cfb649cc9a"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.0.13/arcade-engine_0.0.13_Linux_arm64.tar.gz"
        sha256 "05cf2ca7618412a0d993e38ac412b3217f56b145fae935634f263bd0399c2ebe"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
