# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT139 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.3.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.9/arcade-engine_1.3.9_Darwin_x86_64.tar.gz"
      sha256 "ea07dd14f4c57f28a98528b8777e7444cc287aa25a5b23919c00c838c38ec014"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.9/arcade-engine_1.3.9_Darwin_arm64.tar.gz"
      sha256 "b71b1a3853433374ba7321f8521ae6f4f34b2455eafa02dc3c04ae84be4e1481"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.9/arcade-engine_1.3.9_Linux_x86_64.tar.gz"
      sha256 "6307d5e7e272f6bd72137820449cad7fdeb9a4a24896d51911ad60e1c42d4260"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.9/arcade-engine_1.3.9_Linux_arm64.tar.gz"
      sha256 "be62462039506f71d58bcf87da897a54b7e560213f8d33290efb6938f1ca5eca"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
