# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT108 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.8/arcade-engine_1.0.8_Darwin_x86_64.tar.gz"
      sha256 "0553b6af5ec2a933c66ac1e20bb06f3faedf52242649380bb38974a3aed85612"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.8/arcade-engine_1.0.8_Darwin_arm64.tar.gz"
      sha256 "96a99716cb1c774e6cf4669825f23de07f9a48c960409ebb025dd1afcd1c7fa2"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.8/arcade-engine_1.0.8_Linux_x86_64.tar.gz"
        sha256 "bb0de027a9f12175f61a37953c354c443b2b94754f1fafc9b48f6624705eb2e7"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.8/arcade-engine_1.0.8_Linux_arm64.tar.gz"
        sha256 "3ffc76716edcf3df624d1461249b97c82e9d3e21a4df130a73a88253bc43eab7"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
