# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3336 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.36"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.36/arcade-engine_3.3.36_Darwin_x86_64.tar.gz"
      sha256 "daeb042b0804240f3243f6624d30bafce93960bd30829335e1cb78de0e1ab285"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.36/arcade-engine_3.3.36_Darwin_arm64.tar.gz"
      sha256 "681f2e8b5fdb60091af571444f93271a0993059a653ea00e0833b057bcc1f911"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.36/arcade-engine_3.3.36_Linux_x86_64.tar.gz"
      sha256 "e1dd625815119f24f38a039a952bd93cdf2fc8e70dd1b712348d25e60a94ee8c"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.36/arcade-engine_3.3.36_Linux_arm64.tar.gz"
      sha256 "04148f1c478f48fe4858b8ccea64ff1e4f20e5262ce8b47f7a01413cd1bafd5b"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
