# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3332 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.32"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.32/arcade-engine_3.3.32_Darwin_x86_64.tar.gz"
      sha256 "a1a923353dbcd31588b51e20b2317f57bacdacd8aa83025a2382fa6a6bc2f299"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.32/arcade-engine_3.3.32_Darwin_arm64.tar.gz"
      sha256 "ab81e0068b5d6c0a1fe34e5828d06dac7c7bade951cb37c9172fe7c1c546288c"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.32/arcade-engine_3.3.32_Linux_x86_64.tar.gz"
      sha256 "e03cc4a1fc35ae392606faa953f8a5eebe09ea2398bcf00e885bb08dffb01e3e"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.32/arcade-engine_3.3.32_Linux_arm64.tar.gz"
      sha256 "4d38ee8a2835accf753df134b866ad0b42f2ca35b0478bead40e98c01530c5e4"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
