# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3331 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.31"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.31/arcade-engine_3.3.31_Darwin_x86_64.tar.gz"
      sha256 "ac197017b6d2995113fd0112755c892038f644ae929795c47cc2125101b6eb7a"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.31/arcade-engine_3.3.31_Darwin_arm64.tar.gz"
      sha256 "8b7d1f62d757f9815fb0e7e99e946b118a2977b77611d6464641d986e1bd1f1b"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.31/arcade-engine_3.3.31_Linux_x86_64.tar.gz"
      sha256 "bd41dc36bc79f9a8a0f05b1240452433ac7b9bc4e32317a428b8e86c649de1df"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.31/arcade-engine_3.3.31_Linux_arm64.tar.gz"
      sha256 "2ec96dc47a8d12fac63dbcb2b5923b3d83b86d6368bacaf930f2042dff661571"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
