# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT321 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.1/arcade-engine_3.2.1_Darwin_x86_64.tar.gz"
      sha256 "43c0be2cb7fe81f98364db91282ac7e426b549e1cbb851797b4efaf67900540d"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.1/arcade-engine_3.2.1_Darwin_arm64.tar.gz"
      sha256 "897057d45327a57f9f3a179af3ef7a87192e52dc34e07d5dbf1cb55c3c49c385"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.1/arcade-engine_3.2.1_Linux_x86_64.tar.gz"
      sha256 "88ca7aa3b8c2a6b2e41ef58dd2b9946c14cb36e7b5d8261d8381efab2371a39a"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.1/arcade-engine_3.2.1_Linux_arm64.tar.gz"
      sha256 "74e36db490812851befecbe58081776b96cb69b5efb14a82ebef92fda62408ea"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
