# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT322 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.2/arcade-engine_3.2.2_Darwin_x86_64.tar.gz"
      sha256 "1bdc89e77f4ad86404b88738bd7ef1ec892c88ea536a905f0172020424cb1607"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.2/arcade-engine_3.2.2_Darwin_arm64.tar.gz"
      sha256 "51c10f601c5902dffef5b74315ab16fbb1a71f0b53d38b8276ffb848a39fb7fa"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.2/arcade-engine_3.2.2_Linux_x86_64.tar.gz"
      sha256 "6ef2a624427e773085376fa99b1e0cb26db5f653b43131db07895fc4c9d57922"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.2/arcade-engine_3.2.2_Linux_arm64.tar.gz"
      sha256 "5f204857d44e5a240842e26c273351d8732eb376fcb4d4cf778849a48d4776d5"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
