# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3343 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.43"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.43/arcade-engine_3.3.43_Darwin_x86_64.tar.gz"
      sha256 "995b6874b2899b188c86fc2aec90e91b5447955a545f82f8b59788fed62ce65d"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.43/arcade-engine_3.3.43_Darwin_arm64.tar.gz"
      sha256 "49800f08a56b907014befe5706a749a4db965a92038027d5c00dfe7264314a5e"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.43/arcade-engine_3.3.43_Linux_x86_64.tar.gz"
      sha256 "0c57cf6412e2b2dfe631748b8138198e8d631fe2d8a119162b1f13bd121da599"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.43/arcade-engine_3.3.43_Linux_arm64.tar.gz"
      sha256 "ebe48329ed6dee56f301a97f7dec7364dcd4a9aa017c0fdd9da2a9425ef057db"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
