# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT133 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.3.3"
  depends_on :macos

  on_arm do
    url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.3/arcade-engine_1.3.3_Darwin_arm64.tar.gz"
    sha256 "861eeb3bc4eec4b2a0b9331e093e21bace8aebdbe84eb9a6238f18bfcc2ff132"

    def install
      bin.install "arcade-engine"
      pkgetc.install 'engine.yaml'
      pkgetc.install 'engine.env'
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
