# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT334 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.4/arcade-engine_3.3.4_Darwin_x86_64.tar.gz"
      sha256 "efe999340d95e48f7867de0da5665df94834aa24d3327361875f59a0186be7d9"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.4/arcade-engine_3.3.4_Darwin_arm64.tar.gz"
      sha256 "88588593f4221341967534ac227faa897e5d4cb495c534a63ec7042fd9ccac86"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.4/arcade-engine_3.3.4_Linux_x86_64.tar.gz"
      sha256 "66a2e0e8c78eb5805f5400916370898f1cf9b0a4e8f99824a7d4c839904e8f48"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.4/arcade-engine_3.3.4_Linux_arm64.tar.gz"
      sha256 "86ed4627416623e14437d005a16842b87b5d80476c94ee32c9d5e13c8b568930"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
