# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT306 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.6/arcade-engine_3.0.6_Darwin_x86_64.tar.gz"
      sha256 "dca99da995386b3e353a514b89b7a991369e157e602aa8d8c4ac4d5965c9b81a"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.6/arcade-engine_3.0.6_Darwin_arm64.tar.gz"
      sha256 "b326634f4516ea542e720df69e14853fce8f974bc41eb8472ed56a2a09cee3a3"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.6/arcade-engine_3.0.6_Linux_x86_64.tar.gz"
      sha256 "b12b3ba6744188f7685220a1997d2432d1ca5ddcb9103383d58d4426b79d1cb2"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.6/arcade-engine_3.0.6_Linux_arm64.tar.gz"
      sha256 "cd8e632ef6588289bf28ed17be3ec31770fe693beec6fb931d8ffa08fefb8302"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
