# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT122 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.2/arcade-engine_1.2.2_Darwin_x86_64.tar.gz"
      sha256 "b42857c7144c421fe81845b2cdf6b05ddece40aaebf6d5d12dfaf2c729bb9c1f"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.2/arcade-engine_1.2.2_Darwin_arm64.tar.gz"
      sha256 "edb909774f6cf68d876c9ed50ecd0e50b30b806b2207f4d0ff1e8a39d02166df"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.2/arcade-engine_1.2.2_Linux_x86_64.tar.gz"
        sha256 "1f17a0455828832eebe1a3f755664416480492c8dbf42041a1e3c7c15d30bc2c"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.2/arcade-engine_1.2.2_Linux_arm64.tar.gz"
        sha256 "f801a14ebfe957ad696a61d92e86637e8a4767301f53d5a72cda91ffcca74d9a"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
