# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1228 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.28"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.28/arcade-engine_1.2.28_Darwin_x86_64.tar.gz"
      sha256 "1f8fc9b2c8f54c85c510fea15f6b6fb96cfae5d24e5216b49ca103ae3642c8a3"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.28/arcade-engine_1.2.28_Darwin_arm64.tar.gz"
      sha256 "d16894b1ed76d59aebe5dc9c2c91867456924dab2e31ab24c42a06d6be276e4a"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.28/arcade-engine_1.2.28_Linux_x86_64.tar.gz"
      sha256 "bf942f50f0d78bf8ad93abcd437d5e1ef4899ab8821b88d112dce979e05bc2a2"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.28/arcade-engine_1.2.28_Linux_arm64.tar.gz"
      sha256 "6e7b5518d9bb11e8371c960db60e1b3ab731522c3e73653f6777bc24980288d9"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
