# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1218 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.18/arcade-engine_1.2.18_Darwin_x86_64.tar.gz"
      sha256 "f7396d3122a2c46116a01475fd520a36ea1826fdd3123da45a428ee18e7ed0ee"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.18/arcade-engine_1.2.18_Darwin_arm64.tar.gz"
      sha256 "31001306d76a2322037ce6da00bff8f9f78eeb19745c5699da32dc1f1f2cb3f7"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.18/arcade-engine_1.2.18_Linux_x86_64.tar.gz"
        sha256 "a17bfa4225d8fbf42f150f4cd1b512c9790e37e88b857c9a84e018b5597bcad9"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.18/arcade-engine_1.2.18_Linux_arm64.tar.gz"
        sha256 "ce008e68de49a116ea633eb28415acbeefd423a32ccd7a375089c91e6cc54441"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
