# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT110 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.1.0/arcade-engine_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "43233e11ef6fb631f86fe76ecce0f9bd60fa6c3d1ceba44b22fbc1dfb4e6e9ff"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.1.0/arcade-engine_1.1.0_Darwin_arm64.tar.gz"
      sha256 "23ee549f33ed506e7486da02ce40ce843ba86e317da703a01f240859b15b79fd"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.1.0/arcade-engine_1.1.0_Linux_x86_64.tar.gz"
        sha256 "73d5ea8031b158dcf3ece117102eb36c6e5af44da3c9e4415dbc00a0c1bd4b8a"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.1.0/arcade-engine_1.1.0_Linux_arm64.tar.gz"
        sha256 "f26584e7016f26bfd8c75d52d196ec92c700d6e2c574e13a05c2adb6dc1a5392"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
