# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT310 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.0/arcade-engine_3.1.0_Darwin_x86_64.tar.gz"
      sha256 "498d0f33bdbe1c6786191348814611f9e4ae1d6b035360d5398e5d6bd4b38d43"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.0/arcade-engine_3.1.0_Darwin_arm64.tar.gz"
      sha256 "79420cfe0b4896e9452496520344abf7e2b6de849168dbe505d012cd89ee93f8"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.0/arcade-engine_3.1.0_Linux_x86_64.tar.gz"
      sha256 "281b10c0965e64547dba13b630b1773de9e895adc842c969fb697243951ac0b5"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.0/arcade-engine_3.1.0_Linux_arm64.tar.gz"
      sha256 "a43b9cc9aa675d940683f4e7a744d7a14a7237836cdf59de9f511d8b21420cce"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
