# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3330 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.30"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.30/arcade-engine_3.3.30_Darwin_x86_64.tar.gz"
      sha256 "c7eacc2667ab8a72acab62aa61184d1ac0bc5a19f3211a9a2d15ef05d299a91b"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.30/arcade-engine_3.3.30_Darwin_arm64.tar.gz"
      sha256 "15e7ee185e90f846f70bf69848a0f9986c238af91c920ed9234cb968703bf2e7"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.30/arcade-engine_3.3.30_Linux_x86_64.tar.gz"
      sha256 "a999513d7cb46c5ca8bc080a89b3fa5b4be0f4c71ecd1a1d5b3e96a6ff9798a2"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.30/arcade-engine_3.3.30_Linux_arm64.tar.gz"
      sha256 "240ba7c28897b7045659c0feb2cbf31551708fa5c804400e5c9361deebe547be"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
