# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT313 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.3/arcade-engine_3.1.3_Darwin_x86_64.tar.gz"
      sha256 "f7cb81fefe2ba7cf5309bfe4476e7541eb00dabcc007e6a28d60457a2699a0cc"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.3/arcade-engine_3.1.3_Darwin_arm64.tar.gz"
      sha256 "9e74fe50f9bdf180df44d21628b85c12e77ee663fa8e00b31b9ea9815d0cf5b9"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.3/arcade-engine_3.1.3_Linux_x86_64.tar.gz"
      sha256 "c9c44f8203e73bdd52a68e6ba8b376fac581c9c849acf6befd8078f28ea370a8"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.3/arcade-engine_3.1.3_Linux_arm64.tar.gz"
      sha256 "ce2d688ca114f7bceb387edb4ea55964ad5bfacfa5921eea61dcb303daaabb8c"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
