# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngine < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.0/arcade-engine_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "1c96942f6dd49ffbca1e7f8e219ab36f14af481ca63262beb8a49671ea98e5cf"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.0/arcade-engine_1.3.0_Darwin_arm64.tar.gz"
      sha256 "d5de66037f201192a1e1fd01edd4843bbd9e954e8dd2b537b81692520cd5d8d9"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.0/arcade-engine_1.3.0_Linux_x86_64.tar.gz"
      sha256 "2dbdc1ee3e0b0ab76a2893d2a5c5d6e80fbe181b480a1920fd442df2f7c32d36"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.0/arcade-engine_1.3.0_Linux_arm64.tar.gz"
      sha256 "f5f1ea9a3de0b8b231d0e828fb1c1faba68cde2d80e6587752f181a0c4ac4b0b"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
