# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1017 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.17/arcade-engine_1.0.17_Darwin_x86_64.tar.gz"
      sha256 "e91d18dfd3b267eade48e048dc85fb38d569166aadc2611ed72480afd41e574f"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.17/arcade-engine_1.0.17_Darwin_arm64.tar.gz"
      sha256 "83588aaa114eab22be0cfe958f44abf7a82f889283fec65509aacf91786a35c9"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.17/arcade-engine_1.0.17_Linux_x86_64.tar.gz"
        sha256 "2cb0cdcfd4840a22ca8e0325c211df2b3378ff9f94019b83528039e1f33ca3a0"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.17/arcade-engine_1.0.17_Linux_arm64.tar.gz"
        sha256 "a767b63b48e3adefc1fa1a8062391ae34301575e740298f36184d76644f45d2c"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
