# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT137 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.3.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.7/arcade-engine_1.3.7_Darwin_x86_64.tar.gz"
      sha256 "bfedb116eac80abc6b286b57193ea29162cbfcd882f71320243a868fe8fad844"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.7/arcade-engine_1.3.7_Darwin_arm64.tar.gz"
      sha256 "267f8e20e1d43a4316e60a86f341e4c1554cf388ca92b9b3458570aef3b672da"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.7/arcade-engine_1.3.7_Linux_x86_64.tar.gz"
      sha256 "e384f5651f5bae2a2f75e50a4edb13cce411b963418b1f73510acd0287599c81"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.7/arcade-engine_1.3.7_Linux_arm64.tar.gz"
      sha256 "826e7f5f6c0dbf4cb396a80ba8b6cd5fe3c2032d657566b168959ceb77e9e075"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
