# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3322 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.22/arcade-engine_3.3.22_Darwin_x86_64.tar.gz"
      sha256 "898e58a0dbe08a891aab544e93df80a97a778a7c8f31019c945bc8175fcf243e"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.22/arcade-engine_3.3.22_Darwin_arm64.tar.gz"
      sha256 "c7165497ac35b2a3603d65665fb3a5b0c44647fdd6782af5877f6f63a640bd40"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.22/arcade-engine_3.3.22_Linux_x86_64.tar.gz"
      sha256 "3c5efff3a494edfeeb844eeaae2ba7a133e0e70f597964254185b872e36ff64e"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.22/arcade-engine_3.3.22_Linux_arm64.tar.gz"
      sha256 "3519e4b819bccd6556bd6cb5a6e9e21d894b47a93dd59bf213096fc874c97195"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
