# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT201 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.1/arcade-engine_2.0.1_Darwin_x86_64.tar.gz"
      sha256 "1a37c72ce4e4b2763441d26b0c30f66eae4b6dd361ffb6ae0b7ece331c8018d4"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.1/arcade-engine_2.0.1_Darwin_arm64.tar.gz"
      sha256 "358be0c592dc2a8b5f98a283d8a7016c7df992784b34b6c7da5c59316d1bba51"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.1/arcade-engine_2.0.1_Linux_x86_64.tar.gz"
      sha256 "1706ba318bf1685b6934de913927fb37addbfa6e438e22c01f24c665b7fbf2bd"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.1/arcade-engine_2.0.1_Linux_arm64.tar.gz"
      sha256 "a8a826d6377b3b78a20c1d2b67bd9b063c490b6b494df45454f8dc34e0f3a18c"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
