# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT333 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.3/arcade-engine_3.3.3_Darwin_x86_64.tar.gz"
      sha256 "d439d58c7f59ff4baa07e6897d42bd3e6abf3b6fb14543ff728dbb890d6a5f8d"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.3/arcade-engine_3.3.3_Darwin_arm64.tar.gz"
      sha256 "79ceaf38ace4cf74ea25765f4c176459332194e02d6bb049e7912ffe0c53ac4a"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.3/arcade-engine_3.3.3_Linux_x86_64.tar.gz"
      sha256 "7eded81553f48712da613320ae73787fec4726c181db35c53c96623c86da8844"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.3/arcade-engine_3.3.3_Linux_arm64.tar.gz"
      sha256 "eab8a58230a2e4b50b8c59c2a03da3d7f62cf649cfec9d7a55b7de14674588ca"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
