# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3320 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.20/arcade-engine_3.3.20_Darwin_x86_64.tar.gz"
      sha256 "e64a06ec067b760f5ffc3d960f1460da46a59d4644578ea834d867d7b0f3bd53"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.20/arcade-engine_3.3.20_Darwin_arm64.tar.gz"
      sha256 "908d96d78ec6642064f185d1ceb8aa15b02f506fc0848d25ccee4aba1b51e414"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.20/arcade-engine_3.3.20_Linux_x86_64.tar.gz"
      sha256 "4f295d84c769f17aec49787219e0cce24a53c045c9a7fc39971ebb96f32b9474"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.20/arcade-engine_3.3.20_Linux_arm64.tar.gz"
      sha256 "e4f6c3614df1a7b2640c9c81f6c8c8d49013632187c44112e048014e67369f40"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
