# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1234 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.34"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.34/arcade-engine_1.2.34_Darwin_x86_64.tar.gz"
      sha256 "cd2ac2ee0c091d305cbc860e2e2b6b99b97e7fa52c1f884017b6f837d21aabdc"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.34/arcade-engine_1.2.34_Darwin_arm64.tar.gz"
      sha256 "69a9781d1e9ad499ded7127f7c19a0111bb9880a96677f07ddceb0824d86e048"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.34/arcade-engine_1.2.34_Linux_x86_64.tar.gz"
      sha256 "2321e631acb668b786ebdb0c7669207c57cb3c33aee8211f61fc10cf412b7dfd"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.34/arcade-engine_1.2.34_Linux_arm64.tar.gz"
      sha256 "c311ea9b556d20c9a36603ee314233bf810f6077400eedc357c817885e309855"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
