# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT311 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.1/arcade-engine_3.1.1_Darwin_x86_64.tar.gz"
      sha256 "1b4173d3a993337de55c1d81c22bd8ce18676bf530cf2d74597b3de4d38110ad"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.1/arcade-engine_3.1.1_Darwin_arm64.tar.gz"
      sha256 "91b5e267f2c1e5749832f3b1dbefc95485854241534f1ddad2c78641d8a0b515"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.1/arcade-engine_3.1.1_Linux_x86_64.tar.gz"
      sha256 "c98e37b65c9344dd89d3f05cafd3f14811bb336b35575bf3eb401f00c97c1720"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.1.1/arcade-engine_3.1.1_Linux_arm64.tar.gz"
      sha256 "edd9a49d454f856085ed2aba019aab867a6b4ef583767225c7887a23dbd6b249"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
