# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1312 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.3.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.12/arcade-engine_1.3.12_Darwin_x86_64.tar.gz"
      sha256 "39283ddb978bff4e2abc3102cc43127a6f0039571fd7cb393214a30c82c08afb"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.12/arcade-engine_1.3.12_Darwin_arm64.tar.gz"
      sha256 "37d16ae02fab61a0fa8e06817203220bf6e495ad45191eededb97a253e9e57d1"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.12/arcade-engine_1.3.12_Linux_x86_64.tar.gz"
      sha256 "09fcfbca0bab0fb120f8567a8931711d2f49360f7fec6a402a39e842f8203e02"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.12/arcade-engine_1.3.12_Linux_arm64.tar.gz"
      sha256 "59de133c24c1c9e593c6003083a75e004766f28e8c4bdddcfec607485b635820"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
