# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT120 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.0/arcade-engine_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "88829d47a1161c1e4614896002fd6ea701eedfe1d43821edae5c1cf52fb998e6"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.0/arcade-engine_1.2.0_Darwin_arm64.tar.gz"
      sha256 "f9e7e37caec3928f3bb9c53443d36a2976cdfc2ff041737b339b9959dbdea519"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.0/arcade-engine_1.2.0_Linux_x86_64.tar.gz"
        sha256 "78ed89ed4fdc9d203874d2d6c22096b789df489491fd3f1ea33295cb919b54a6"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.0/arcade-engine_1.2.0_Linux_arm64.tar.gz"
        sha256 "ca4631d34818c85e90f506f3e08e68fd23160b074fe076c18090b6bdad34063d"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
