# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3318 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.18/arcade-engine_3.3.18_Darwin_x86_64.tar.gz"
      sha256 "f7b3536175d6f4c8d223b273cf98b3ab2dbb45a5b243f45800cd918ae64834d5"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.18/arcade-engine_3.3.18_Darwin_arm64.tar.gz"
      sha256 "a2c6813bc6fa0f0d695d52c6619747f8487c17d7bf96ae42136f8a41df2491dd"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.18/arcade-engine_3.3.18_Linux_x86_64.tar.gz"
      sha256 "259445c2c733c49a2934b87e55484dd97b9f964fc506d6941a40b0852e34ba0a"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.18/arcade-engine_3.3.18_Linux_arm64.tar.gz"
      sha256 "fd0558461f83b0f3147de50180b1578309684cbf32ac52c14bc5b02b77f7af6c"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
