# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT011 < Formula
  desc "Engine for ArcadeAI"
  homepage "https://arcade-ai.com/"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.1/arcade-engine_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "6f201eabbbd067392f39bfca250d713dbae8b762f1b40c3ea29ea33d59dd5463"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
    on_arm do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.1/arcade-engine_0.1.1_Darwin_arm64.tar.gz"
      sha256 "1c672fc513bbeeded9d272b01368255e5aa22d09308c050961e063cc537e4dbf"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.1/arcade-engine_0.1.1_Linux_x86_64.tar.gz"
        sha256 "76a26b1d6173456d64f16fe642afc963c8feade5b12acb862edc75a1b745863b"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.1/arcade-engine_0.1.1_Linux_armv6.tar.gz"
        sha256 "8dd61f2b87699dce9cf47ceb98c2f5f621d953338f717d1f310a5a7e028259d2"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.1/arcade-engine_0.1.1_Linux_arm64.tar.gz"
        sha256 "b8e0d032dfcaeb30dac4e79a507ad188290c46bd4a6ed65666ec15f763db3125"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
