# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT125 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.5/arcade-engine_1.2.5_Darwin_x86_64.tar.gz"
      sha256 "00c707288e35daa56c2a00395b9d50b5d89ba2ad757b7c30ddad5406f25bda22"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.5/arcade-engine_1.2.5_Darwin_arm64.tar.gz"
      sha256 "69a32bbf9aae01a52222a2ee2b937f17a24a1e8d01e6ca726cb26697ccba0b89"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.5/arcade-engine_1.2.5_Linux_x86_64.tar.gz"
        sha256 "80635b1e856630035bad75cc3cebfbff2d95ef5d711bd050b12464faeba17716"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.5/arcade-engine_1.2.5_Linux_arm64.tar.gz"
        sha256 "8f1e40c9d548ee143115cf38a1a699f6519e9456ec2e83b9546ed45949686220"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
