# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT107 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.7/arcade-engine_1.0.7_Darwin_x86_64.tar.gz"
      sha256 "6d874cf56c3b93fad4527ab7490f6b545f0fd83825339a98d5b6c4ba74e4d700"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.7/arcade-engine_1.0.7_Darwin_arm64.tar.gz"
      sha256 "5ca6567532854327bf111a2fb2ed97e141ccc059b8fbee23edb66a39063d7039"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.7/arcade-engine_1.0.7_Linux_x86_64.tar.gz"
        sha256 "97b5a1bc464312c8ae6b4c7a0b093e7b99bbd80bdc6df1915223f19dec85b3a4"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.7/arcade-engine_1.0.7_Linux_arm64.tar.gz"
        sha256 "080922da3a5358e2bbe031ac2079f57014098d0a05a86cb962c02255d8c4fc52"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
