# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT339 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.9/arcade-engine_3.3.9_Darwin_x86_64.tar.gz"
      sha256 "b0dbf947ab6ef409c75df782d7b539fb6c15d3c2cd0b4a4224610ba089d38347"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.9/arcade-engine_3.3.9_Darwin_arm64.tar.gz"
      sha256 "016705a1d60b5dd33a5ba6d242fdaa1db82875f134095f6c6ac778845b51012e"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.9/arcade-engine_3.3.9_Linux_x86_64.tar.gz"
      sha256 "1c9a6de91d4e950ef853c2933ad4062618e81fbc3391e976059580260212476e"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.9/arcade-engine_3.3.9_Linux_arm64.tar.gz"
      sha256 "877981395b6536379fd722c281b40daaf1d65f09c41c023f411ddcf58a43fcf2"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
