# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1231 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.31"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.31/arcade-engine_1.2.31_Darwin_x86_64.tar.gz"
      sha256 "9867068e79d128192059424bd72b5b99f886e939610a3627ebb17e0fb03e927b"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.31/arcade-engine_1.2.31_Darwin_arm64.tar.gz"
      sha256 "53d1029706ad5c56f825da93c5410704a8fc41221e8afa7900670e0cdf1ebb74"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.31/arcade-engine_1.2.31_Linux_x86_64.tar.gz"
      sha256 "d859f7f1cd1a28b7fe799ce1142ee545144f45f6521aadb9beda5a0676a945eb"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.31/arcade-engine_1.2.31_Linux_arm64.tar.gz"
      sha256 "6301a51bd7a07003e0e393ccd063c24eee011c0c864fb99ed1e18e38a8dafaec"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
