# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3321 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.21/arcade-engine_3.3.21_Darwin_x86_64.tar.gz"
      sha256 "fd8c15173ecb6edcc2b86b6ba1b928d0156ff0389dfd2014a3fcb0f362d13601"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.21/arcade-engine_3.3.21_Darwin_arm64.tar.gz"
      sha256 "219651474e8dede144943a301e8ac465fcf4a4ca2bb4c65c75109d89ba8a782f"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.21/arcade-engine_3.3.21_Linux_x86_64.tar.gz"
      sha256 "10654ad17e6727f0f8adb202a7cb64ebd0a6e90bbfc95959624273fa091605b3"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.21/arcade-engine_3.3.21_Linux_arm64.tar.gz"
      sha256 "b9a01e5b5b031dbeadc1006defd6f149e034c52a152db53b4ef88a2635d3d4ea"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
