# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3338 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.38"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.38/arcade-engine_3.3.38_Darwin_x86_64.tar.gz"
      sha256 "fd4927af83527f5b5991aef31322e1318b4efdf670ea36d95910808982aa0c30"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.38/arcade-engine_3.3.38_Darwin_arm64.tar.gz"
      sha256 "d8ae52831b4999b4be7b56507ea03a747a811eb110657f9d62ad49b2054afedc"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.38/arcade-engine_3.3.38_Linux_x86_64.tar.gz"
      sha256 "191e753e67f3a631e38b6f0755340940c134922aa4116bcc7b7085ac85d7f0d6"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.38/arcade-engine_3.3.38_Linux_arm64.tar.gz"
      sha256 "b2e4f9276d08c282c12c6a2206b6288ac690f5d35537509c0be84aaffbee192f"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
