# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT106 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.6/arcade-engine_1.0.6_Darwin_x86_64.tar.gz"
      sha256 "90677b6c7aaa8552fb29a9c40c30acba443fe919ee0f9617fbc7b2e7759477c2"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.6/arcade-engine_1.0.6_Darwin_arm64.tar.gz"
      sha256 "7aaa30c73153d24142ec6c53f719278dee0d4ca5fe9e7b5e76c4f6ca8a2021f3"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.6/arcade-engine_1.0.6_Linux_x86_64.tar.gz"
        sha256 "6aac7e38e356edcafd3f87a0838de76ebf84ba40f9435b2db004d4bab6a7fc80"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.6/arcade-engine_1.0.6_Linux_arm64.tar.gz"
        sha256 "0a8ae14e1f561e20ab1c9c07df6f601f6ae97d38d99768c7d181ae77c908d138"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
