# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT109 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.9/arcade-engine_1.0.9_Darwin_x86_64.tar.gz"
      sha256 "8c5c23e4c767e9e20d5aea342b1fc5e9d8524e5468872595fce0300b9f8db977"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.9/arcade-engine_1.0.9_Darwin_arm64.tar.gz"
      sha256 "d612241bc09806cd02b07d2a1ff5213c087c0433eaef8c34818f63ba75feef8e"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.9/arcade-engine_1.0.9_Linux_x86_64.tar.gz"
        sha256 "2d517bbb0f7bf5ba62296fb583da902123701229671e6394ef23f4c793dcc036"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.9/arcade-engine_1.0.9_Linux_arm64.tar.gz"
        sha256 "da95d04479b12e77898103869882996ee6e05ca214f59c7eb02953a4c6c7754d"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
