# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3315 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.15/arcade-engine_3.3.15_Darwin_x86_64.tar.gz"
      sha256 "575870535e39dec25adb3ec796e99138e5628c2d882d09a82c2fba43a5735a71"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.15/arcade-engine_3.3.15_Darwin_arm64.tar.gz"
      sha256 "238b34f8dd4939ac8bcad45f79feb555cc8d3b3905628418cb2356dda389c6b6"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.15/arcade-engine_3.3.15_Linux_x86_64.tar.gz"
      sha256 "3c4cf5dad06f747311e305ed9581ff5bb31c32aac4cbf856adb854553f0fe660"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.15/arcade-engine_3.3.15_Linux_arm64.tar.gz"
      sha256 "4d785cf3c1b42361c4eeb5e62d109baec9472dc12a376c15e20c6ae687f38740"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
