# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT129 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.9/arcade-engine_1.2.9_Darwin_x86_64.tar.gz"
      sha256 "ff7ced2bd9ce2dea288e9c244cf6397b75627bccd62a6e24b662ea98aadf0f39"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.9/arcade-engine_1.2.9_Darwin_arm64.tar.gz"
      sha256 "b232f5b276ece60fe5d5e32b743b3c10bb9beca4f151894f22e0c556d1a77bdc"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.9/arcade-engine_1.2.9_Linux_x86_64.tar.gz"
        sha256 "431d31648e0c62db43a00ad40e2bac3c6a9421f805955e0984b1a740caac4e3f"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.9/arcade-engine_1.2.9_Linux_arm64.tar.gz"
        sha256 "ae330d7283f275a102a796d4153827f616287041624d22317a6c5ef3f96fea4f"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
