# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1019 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.19/arcade-engine_1.0.19_Darwin_x86_64.tar.gz"
      sha256 "ab2c6d28d499805397dd8d157016cbd478ba098fb198ca922b235fd164e24204"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.19/arcade-engine_1.0.19_Darwin_arm64.tar.gz"
      sha256 "4725df6d2e49c2f0f88ca0206d98ca5ee275801b568991bbb78548a870d442c4"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.19/arcade-engine_1.0.19_Linux_x86_64.tar.gz"
        sha256 "553a4cfc4492d1a87028f16784652413d2c99f363c8abfff8f2bf5c28fa85656"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.19/arcade-engine_1.0.19_Linux_arm64.tar.gz"
        sha256 "ca638df07846acbd7fe6ffafd82254e02962fd1bde11b203bccf510c229ae779"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
