# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngine < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.41"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.41/arcade-engine_3.3.41_Darwin_x86_64.tar.gz"
      sha256 "4421f87ce5a0085aa41ecc977aa625247df0a331527a39ff998be91e2eff2e94"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.41/arcade-engine_3.3.41_Darwin_arm64.tar.gz"
      sha256 "60e6421fa9a4a7e59a1ceb6b48a988e34cf354e719023c452d0f55c057090913"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.41/arcade-engine_3.3.41_Linux_x86_64.tar.gz"
      sha256 "f4cb1044bf7a21162d5b666b5ac15b76ec8e478397ee04a1fb5074bb9dadb298"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.41/arcade-engine_3.3.41_Linux_arm64.tar.gz"
      sha256 "7df513c62ae7df3917493cc6d788068c5728cd2428cc1d00783c2b8cb00ea282"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
