# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3323 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.23/arcade-engine_3.3.23_Darwin_x86_64.tar.gz"
      sha256 "82124c822f156ee36e367fdfe0397830e28e73d84eaac3bf5fa41c11a28e3f54"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.23/arcade-engine_3.3.23_Darwin_arm64.tar.gz"
      sha256 "bdb50a07f7e85695a110c9332fba3ba93e15f1e66445b3e74f8badcdd4102888"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.23/arcade-engine_3.3.23_Linux_x86_64.tar.gz"
      sha256 "8d730812660d779e64e3fb6f6116664eb6799ddb381fb536d3010d69a08c4f61"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.23/arcade-engine_3.3.23_Linux_arm64.tar.gz"
      sha256 "25e38581d04d8e8857372a18696ca244eaf8093bd90db5edb84b4ba0006a14b6"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
