# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT337 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.7/arcade-engine_3.3.7_Darwin_x86_64.tar.gz"
      sha256 "2023c6a805d166b09baf198a417ff9749d1c2dc4b4418e5481f0238915cdc11d"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.7/arcade-engine_3.3.7_Darwin_arm64.tar.gz"
      sha256 "d6de9dcd665db37a5b94070828514a85da35c39049a2322817632bdb01f9aa40"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.7/arcade-engine_3.3.7_Linux_x86_64.tar.gz"
      sha256 "7fbf4f85e2d2bb4684828864481180a4599e974d22365b78a9e5b9521a9ca83d"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.7/arcade-engine_3.3.7_Linux_arm64.tar.gz"
      sha256 "b6ed0e6b9321965511c063e29e05273137e397c2c8a5326540efa2a9af1bb4b4"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
