# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT010 < Formula
  desc "Engine for ArcadeAI"
  homepage "https://arcade-ai.com/"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.0/arcade-engine_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "f6b56f29c79dbb083db64aa529ca112e08869d4e672ecd4ee1a9b1ba97be161f"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
    on_arm do
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.0/arcade-engine_0.1.0_Darwin_arm64.tar.gz"
      sha256 "20de25826a31c64f5e86e9fac734966c8898eb5749263421135b58105eef819e"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.0/arcade-engine_0.1.0_Linux_x86_64.tar.gz"
        sha256 "d8fffd26c110b6ee11dc2a4ad1a5ad280d6ada8cc325f5a93f94064adbdb8548"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.0/arcade-engine_0.1.0_Linux_armv6.tar.gz"
        sha256 "81bcd47a2908305ea45d67de55ca08cdc45b0cf43e9f23d60e29bc39b6b1b5ac"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v0.1.0/arcade-engine_0.1.0_Linux_arm64.tar.gz"
        sha256 "40ef989db6e7808ff9a61d0d9197ab43682c1921c35976ab60005478959fdb1d"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
