# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT202 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "2.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.2/arcade-engine_2.0.2_Darwin_x86_64.tar.gz"
      sha256 "fcb53a5f78d6e0e00a1e2f81c69392ba71ced283641f405b8c6cc409a66fda83"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.2/arcade-engine_2.0.2_Darwin_arm64.tar.gz"
      sha256 "9d7ba0422229117b852eb1f31635dddc5f47df6049055f5688b26087fd7dfdf4"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.2/arcade-engine_2.0.2_Linux_x86_64.tar.gz"
      sha256 "28864fed2df107bb18a9e196b70b95a02cfeab9ed92c2796ce2d7c895c4d62ea"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v2.0.2/arcade-engine_2.0.2_Linux_arm64.tar.gz"
      sha256 "dbefc220b09191df99af991f682796bfbb62f0204586450263afaddd9d13518a"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
