# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT330 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.0/arcade-engine_3.3.0_Darwin_x86_64.tar.gz"
      sha256 "7ddce26a7df4d624965795f97ccc53078bb4c466b8a475c55f7b28fa7a7cfaeb"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.0/arcade-engine_3.3.0_Darwin_arm64.tar.gz"
      sha256 "daaf4be1eb8c93b6459f7f770b58ee7315796db0739b8c1f7b85e9ed8852cd8c"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.0/arcade-engine_3.3.0_Linux_x86_64.tar.gz"
      sha256 "ac65ffe7702949164bc0363803a8381a21f61fa6064d27a046d334bd51b6af1d"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.0/arcade-engine_3.3.0_Linux_arm64.tar.gz"
      sha256 "eed7b580679058c2c4ea379cbc88a5f59c232b97839e50586200ea811da2afd1"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
