# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3317 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.17/arcade-engine_3.3.17_Darwin_x86_64.tar.gz"
      sha256 "499f4be57868d65ddbd1ed8cc09921a191a258bcfdad54a911a68a5b211dd7e8"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.17/arcade-engine_3.3.17_Darwin_arm64.tar.gz"
      sha256 "ab4a16658e1e2a709e48c7ccf46e602954106213a7ef8d32e93ef12d59466fee"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.17/arcade-engine_3.3.17_Linux_x86_64.tar.gz"
      sha256 "a4bebd764c83fc11b4ffa0d379df726c6cd180c0d0887298de135c5dae4078a2"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.17/arcade-engine_3.3.17_Linux_arm64.tar.gz"
      sha256 "19703541a8cd93a197d1d8ed2d4d09a5b0342b2a00d246d8df8cf6725dc62a4c"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
