# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1014 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.14/arcade-engine_1.0.14_Darwin_x86_64.tar.gz"
      sha256 "ce13a2871d460d073b94a75e862a91891944bdf1842cf338b277a7af9280c979"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.14/arcade-engine_1.0.14_Darwin_arm64.tar.gz"
      sha256 "c0d01e039563cc0b2d9446cc453d098b9bec35b27627f3d0c1398eef4b3091bc"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.14/arcade-engine_1.0.14_Linux_x86_64.tar.gz"
        sha256 "1b32a4eebace001de680d7a3941d2847f3704723d489878feabded17bed7206a"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.0.14/arcade-engine_1.0.14_Linux_arm64.tar.gz"
        sha256 "2cc348d8cdb9d2450d41fbeb60ae8932ad13224331bff6a8d8539f0de449f419"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
