# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3339 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.39"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.39/arcade-engine_3.3.39_Darwin_x86_64.tar.gz"
      sha256 "d8a3a4e0eab0eb8a972b86d7eede61f0b5383036d5644935eead2e45bca1d2ac"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.39/arcade-engine_3.3.39_Darwin_arm64.tar.gz"
      sha256 "17a6959f20ce2933cc5cfca9b3d892a4f8626cfecd804fb6c4d05a4404872c34"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.39/arcade-engine_3.3.39_Linux_x86_64.tar.gz"
      sha256 "639aa1ad72cdf4df0dc81a669244f27bc0aa7b6d182fcf4b733b404da5daad5f"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.39/arcade-engine_3.3.39_Linux_arm64.tar.gz"
      sha256 "4f668b4f17f0c96ccbb4d8d6a7071a5b3aef35e3cb83985a6bbeeffc1262bf07"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
