# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT121 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.1/arcade-engine_1.2.1_Darwin_x86_64.tar.gz"
      sha256 "824f1ce1c49e254efcb08f61a02c7244ad5a8d5247587a8156a1fd109c04631b"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.1/arcade-engine_1.2.1_Darwin_arm64.tar.gz"
      sha256 "9430f8b62589d8716063a5a6fbf9ff31d896bc78117b28a32ddb639908b3b691"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.1/arcade-engine_1.2.1_Linux_x86_64.tar.gz"
        sha256 "fd2a5e30b8e50bdb33c23406eac1ef8565a91cb5ca73259037b580b1a71101f3"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.1/arcade-engine_1.2.1_Linux_arm64.tar.gz"
        sha256 "ab5c52b42b08335cd578cd72e2ba0f7996b38aac3691a49d9c2e575be3813ced"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
