# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT320 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.0/arcade-engine_3.2.0_Darwin_x86_64.tar.gz"
      sha256 "61c82fe497e75781ddba42f6f1390877aaa636d55fb858d8eb5e2260df2cc329"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.0/arcade-engine_3.2.0_Darwin_arm64.tar.gz"
      sha256 "4c32a77345212bb775500a30bcfd14ed7466fd63aee3fde51e9a24e596ede403"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.0/arcade-engine_3.2.0_Linux_x86_64.tar.gz"
      sha256 "e8f5a15ef572125d990fdbcc1bbad9ba10150d1a3e70b68783ebbad4891a59b1"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.2.0/arcade-engine_3.2.0_Linux_arm64.tar.gz"
      sha256 "2436ec57bf0abae4c8a0d77c2033ad39a3c57bac5866e8a2dc7e08dffcba73db"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
