# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1223 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.23/arcade-engine_1.2.23_Darwin_x86_64.tar.gz"
      sha256 "63e57e71085eea0f2c4d144551d96dff8b151ffca16e5553034bd7e0ea8ad3b5"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.23/arcade-engine_1.2.23_Darwin_arm64.tar.gz"
      sha256 "49ec717e709a122b41d4c045e2e0f6993f4e5470383bef02201adb8f75472f2e"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.23/arcade-engine_1.2.23_Linux_x86_64.tar.gz"
        sha256 "83fe3e5699c49ffb094b7faef103b1f97738a7cf913d00120bc933948b915f93"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.23/arcade-engine_1.2.23_Linux_arm64.tar.gz"
        sha256 "9d9a7abbd48c923cf937fae32f2d84493734a19754aedad68884454e053b5dbf"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
