# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT134 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.4/arcade-engine_1.3.4_Darwin_x86_64.tar.gz"
      sha256 "5797cefe86e9df71f9dc69820152e93be57d051ea68185e1f7aa16344c2bc295"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.4/arcade-engine_1.3.4_Darwin_arm64.tar.gz"
      sha256 "4f8ed268aa8132f32a1c8a314f4c0095e8915a728c5a74df3c8be5152497fb78"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.4/arcade-engine_1.3.4_Linux_x86_64.tar.gz"
      sha256 "ed4b9502d4f84707e339a77efd9adcde2c0bae46dc31dcadf295b81cd7564a4f"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.3.4/arcade-engine_1.3.4_Linux_arm64.tar.gz"
      sha256 "1d1e986187af31074e74ab6cb5ef6eced218f2e3e5f63b4810b6fb2f1da73891"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
