# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT3311 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.11/arcade-engine_3.3.11_Darwin_x86_64.tar.gz"
      sha256 "f8f4fa142242da5bc67736023a64300be13fa215d0c909d6ce477541e9fb1ac6"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.11/arcade-engine_3.3.11_Darwin_arm64.tar.gz"
      sha256 "b8522529b9d19121630f56f1212167cb005b2bedebfdf38755a6f3776c9a807c"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.11/arcade-engine_3.3.11_Linux_x86_64.tar.gz"
      sha256 "95759a350c88855f54ab4c7f3320fdd8f35f3f59edb4a55d9132492e363761b1"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.11/arcade-engine_3.3.11_Linux_arm64.tar.gz"
      sha256 "a20b9754e4912356e6d1dd59e744aa7219ab9191c61e51bb9ea802e1c683cb7d"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
