# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT301 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.1/arcade-engine_3.0.1_Darwin_x86_64.tar.gz"
      sha256 "a1fafee0eb2301d9033e23956366b34dba5968e413798acf8ea06aea2ea218e0"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.1/arcade-engine_3.0.1_Darwin_arm64.tar.gz"
      sha256 "0a573d9c94133874f5af2e484191979a91108265a22cb49e58643c3758e76c5e"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.1/arcade-engine_3.0.1_Linux_x86_64.tar.gz"
      sha256 "d2f6bcb9c53eb41b2fdccd1d0301d747d18045cfc41eaa9caad853e70b8c74a4"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.0.1/arcade-engine_3.0.1_Linux_arm64.tar.gz"
      sha256 "13cac7647cceaf99159750b24fb69e6394ebc8731e070ec1cb230fc2f565e8f7"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
