# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1212 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.12/arcade-engine_1.2.12_Darwin_x86_64.tar.gz"
      sha256 "9621d633f62edfff341cd2320b5984c91561b432b0ea0cc0008fdbb4248c3d69"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.12/arcade-engine_1.2.12_Darwin_arm64.tar.gz"
      sha256 "2ca1c1d98cc1e0b797100d9db1883e2bda9982f6d3d679f695e9deef67755877"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.12/arcade-engine_1.2.12_Linux_x86_64.tar.gz"
        sha256 "4d60e19e1bafd9f9da531ca6ff3dfa8862562b752a8b959e0332765dd8bb2f1a"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.12/arcade-engine_1.2.12_Linux_arm64.tar.gz"
        sha256 "c00f9f730cc64e1cae34cf5435b7d531649d314e22479f1fe53a9b66e13d4622"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
