# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT331 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.1/arcade-engine_3.3.1_Darwin_x86_64.tar.gz"
      sha256 "6492f79b62d56447c6c6c894aac1cb121fda1f7bb44b14729b6437da16504f7f"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.1/arcade-engine_3.3.1_Darwin_arm64.tar.gz"
      sha256 "f41c7b5fdd912c69a2512eb12049a904e8dd89dca6f0562b67b5023f84739043"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.1/arcade-engine_3.3.1_Linux_x86_64.tar.gz"
      sha256 "d225a6245b5f0fdaca80cd8e7bac8ee15c79535be4c851d5cba9374513c94a07"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.1/arcade-engine_3.3.1_Linux_arm64.tar.gz"
      sha256 "1ab54d065b5df7184d97a8637126ac3b2d1f8a4f0086301fd5442034a40bfd8c"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
