# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT338 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "3.3.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.8/arcade-engine_3.3.8_Darwin_x86_64.tar.gz"
      sha256 "7749bd039b6b951224209ae13a1cb008b25732fcc271fdd62ccd27d9c8cb0dbd"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.8/arcade-engine_3.3.8_Darwin_arm64.tar.gz"
      sha256 "a2dbd9617e9329499e59b7d60b333abf217e18441e8d9d4f26e200dbe9df199c"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.8/arcade-engine_3.3.8_Linux_x86_64.tar.gz"
      sha256 "fa73d223cfacd25c72e0f676a844ec289fa9d3dd025c9747e1f4c1fec14fac53"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v3.3.8/arcade-engine_3.3.8_Linux_arm64.tar.gz"
      sha256 "702d7420095e40ede6caebe2657d3a1acfdf5e6c648a8b5f5646360c331f4be7"
      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
