# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArcadeEngineAT1215 < Formula
  desc "Engine for Arcade"
  homepage "https://arcade.dev/"
  version "1.2.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.15/arcade-engine_1.2.15_Darwin_x86_64.tar.gz"
      sha256 "c48305c2f84a252d63a056f36cf0488fe0c3217075487974c819647d318df781"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
    if Hardware::CPU.arm?
      url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.15/arcade-engine_1.2.15_Darwin_arm64.tar.gz"
      sha256 "e73ff95fd876746f9af0cc0ff0b910fc78ae083acface0738a531904fad5841c"

      def install
        bin.install "arcade-engine"
        pkgetc.install 'engine.yaml'
        pkgetc.install 'engine.env'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.15/arcade-engine_1.2.15_Linux_x86_64.tar.gz"
        sha256 "c6ddba31cc2ed612d640774142b53261f8bfc80c3430fb393ff3138183fad9df"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://arcadeai-releases.s3.amazonaws.com/macos/v1.2.15/arcade-engine_1.2.15_Linux_arm64.tar.gz"
        sha256 "789139786bf6752d861ccc5ff74619ee43012e756ed9728dbf13b2b0929bb9fb"

        def install
          bin.install "arcade-engine"
          pkgetc.install 'engine.yaml'
          pkgetc.install 'engine.env'
        end
      end
    end
  end

  head "https://github.com/ArcadeAI/homebrew-tap.git"
end
